baseURL = 'https://doublecloud999.github.io'
languageCode = 'zh-cn'
title = '技术笔记'
theme = 'PaperMod'

[params]
  author = 'doublecloud999'
  description = '记录技术学习过程'
  defaultTheme = 'auto'

[params.profileMode]
  enabled = true
  title = "你好"
  subtitle = "记录技术学习过程"

[[menu.main]]
  name = '首页'
  url = '/'
  weight = 10

[[menu.main]]
  name = '文章'
  url = '/posts/'
  weight = 20

[[menu.main]]
  name = '标签'
  url = '/tags/'
  weight = 30